name: Trigger chores

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Main"]
    branches:
    - main
    types:
    - completed

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    - name: Dump environment variables
      run: set
  trigger-chores:
    name: Trigger chores
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    strategy:
      matrix:
        repo:
        - ArloL/abenteuer-irland
        - ArloL/arlol.github.io
        - ArloL/business-english
        - ArloL/chorito
        - ArloL/dotfiles
        - ArloL/eclipse-projects
        - ArloL/gitfx
        - ArloL/mvnx
        - ArloL/newlinechecker
        - ArloL/wait-for-ports
        - ArloL/website-janitor
        - sprinteins/drupal-client
    steps:
    - name: Trigger chores on ${{ matrix.repo }}
      uses: peter-evans/repository-dispatch@v2.1.2
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ matrix.repo }}
        event-type: chores
