name: Trigger chores

on:
  workflow_run:
    workflows: ["Main"]
    branches: [main]
    types:
    - completed

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"
  trigger-chores:
    name: Trigger chores
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Trigger chores on ArloL/chorito
      run: |
        curl \
          --request POST \
          --header "Accept: application/vnd.github.everest-preview+json" \
          --header "Authorization: token ${{ secrets.PAT }}" \
          --data '{"event_type": "chores"}' \
          https://api.github.com/repos/ArloL/chorito/dispatches
    - name: Trigger chores on ArloL/chorito
      run: |
        curl \
          --request POST \
          --header "Accept: application/vnd.github.everest-preview+json" \
          --header "Authorization: token ${{ secrets.PAT }}" \
          --data '{"event_type": "chores"}' \
          https://api.github.com/repos/ArloL/dotfiles/dispatches
    - name: Trigger chores on ArloL/chorito
      run: |
        curl \
          --request POST \
          --header "Accept: application/vnd.github.everest-preview+json" \
          --header "Authorization: token ${{ secrets.PAT }}" \
          --data '{"event_type": "chores"}' \
          https://api.github.com/repos/ArloL/gitfx/dispatches
    - name: Trigger chores on ArloL/chorito
      run: |
        curl \
          --request POST \
          --header "Accept: application/vnd.github.everest-preview+json" \
          --header "Authorization: token ${{ secrets.PAT }}" \
          --data '{"event_type": "chores"}' \
          https://api.github.com/repos/ArloL/mvnx/dispatches
    - name: Trigger chores on ArloL/chorito
      run: |
        curl \
          --request POST \
          --header "Accept: application/vnd.github.everest-preview+json" \
          --header "Authorization: token ${{ secrets.PAT }}" \
          --data '{"event_type": "chores"}' \
          https://api.github.com/repos/ArloL/newlinechecker/dispatches
    - name: Trigger chores on ArloL/chorito
      run: |
        curl \
          --request POST \
          --header "Accept: application/vnd.github.everest-preview+json" \
          --header "Authorization: token ${{ secrets.PAT }}" \
          --data '{"event_type": "chores"}' \
          https://api.github.com/repos/ArloL/wait-for-ports/dispatches
